#!/bin/bash
mkdir -p testCatalog/from
mkdir -p testCatalog/to
printf "Lorem" > testCatalog/from/loremShort.txt

printf "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus scelerisque ultricies ante at lobortis. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nullam vel augue ut nunc varius gravida. Quisque tellus magna, pulvinar eu risus id, placerat hendrerit metus. Nullam nec tincidunt nibh. Mauris sagittis lorem a consequat laoreet. Phasellus luctus, lorem nec imperdiet porttitor, dui ligula hendrerit massa, id posuere erat felis vitae quam. Sed justo quam, finibus non erat eu, sollicitudin elementum magna. Donec bibendum purus et diam fringilla facilisis vitae sit amet diam. Praesent non consectetur lacus. Praesent diam felis, mattis ac nibh eget, vehicula lobortis neque. Ut est orci, finibus non pellentesque ut, semper sagittis magna. Curabitur venenatis ex lorem, ut congue odio auctor nec." >testCatalog/from/lorem.txt

printf "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam feugiat odio eros, sed vehicula lectus gravida sed. Praesent sed turpis ac magna pretium auctor ac a nulla. Mauris nunc tellus, vulputate sit amet suscipit nec, imperdiet at justo. Vestibulum interdum eget libero vitae posuere. Ut gravida, ligula et tempus auctor, neque lacus convallis lectus, quis euismod dolor purus in metus. Proin pellentesque odio eu erat dictum hendrerit. Nulla scelerisque ac felis vitae laoreet. Morbi auctor egestas nisi, in condimentum risus egestas nec. Sed aliquet risus vitae ex vehicula, id scelerisque eros sagittis. Sed eu semper augue. Phasellus eget nibh at lorem fermentum placerat. Morbi bibendum ultrices purus, at semper risus rutrum eget. Etiam condimentum faucibus ipsum, sed dapibus dolor pellentesque vitae. Donec congue placerat velit, ac tristique ipsum blandit vitae. Integer et tempor enim, posuere finibus velit. Curabitur quis dui porttitor, venenatis sem quis, interdum diam.
Suspendisse pellentesque ex ut enim vestibulum dignissim. Donec in fringilla ipsum. Phasellus eu enim quis dolor convallis sodales in id erat. Integer dignissim ligula sed magna pretium vestibulum. Phasellus mollis dictum ipsum, non posuere tellus fermentum et. Maecenas non laoreet tortor. Quisque euismod euismod dui, vel luctus diam. Aliquam odio ipsum, congue vitae placerat eu, convallis quis ipsum. Integer massa eros, euismod eu suscipit non, ullamcorper vel sem. Nam dui mauris, finibus eget bibendum sed, ullamcorper et leo. Aliquam congue vulputate nibh, id ornare tellus consectetur sed.
Nam ut egestas ante. Cras dolor lectus, tempus et faucibus a, porta id turpis. Quisque mollis rhoncus pretium. Mauris quis volutpat metus. Proin leo tellus, consequat vel porttitor a, dictum sed arcu. Proin dictum facilisis orci, ac mollis lectus accumsan in. Mauris placerat ipsum metus, vel sagittis magna porta nec. Phasellus rutrum blandit lorem a tempus. Vivamus ut placerat ipsum.
Suspendisse dictum blandit dolor, vel elementum nulla consectetur eu. Nam vitae feugiat diam. Nullam dui lacus, porttitor non lacus sit amet, lobortis semper neque. Nam varius quam at metus tincidunt, sit amet gravida enim bibendum. Duis a diam vulputate, eleifend nisi id, dapibus augue. Nam id blandit tellus. Mauris lacinia ex sit amet est tempor luctus. Donec consequat pellentesque enim, id dapibus ex. Curabitur nec dignissim felis, eu molestie mauris. Aenean nec interdum odio. Sed ac tristique erat.
Curabitur lectus risus, malesuada nec justo eu, commodo pretium libero. Nullam aliquet maximus iaculis. Mauris consequat pharetra eros quis ornare. Vivamus pharetra, velit vel tincidunt viverra, diam sapien euismod dolor, eu euismod lacus nibh sit amet magna. Vestibulum magna nulla, vulputate ac sollicitudin id, sagittis ac arcu. Vivamus pharetra maximus erat, et bibendum arcu placerat eget. Mauris nec tortor id mi molestie ultrices. Integer convallis tempor tellus at consequat.
Nullam eget elementum ante. Curabitur mauris diam, porttitor id neque sit amet, imperdiet rutrum nisl. Etiam eget nisi sit amet nibh fringilla mollis at ac turpis. Sed id mi non nisl commodo ultricies. In hac habitasse platea dictumst. Morbi odio arcu, hendrerit at risus vitae, consectetur pretium enim. Ut eu rutrum dui, ultrices sagittis dui. Etiam vestibulum turpis massa, nec scelerisque diam hendrerit nec. Aliquam erat volutpat. Cras vitae tellus at sem tincidunt egestas. Cras nisl justo, eleifend a accumsan sit amet, vulputate quis sapien. Curabitur efficitur elementum lorem.
Praesent bibendum, velit vitae pulvinar tempor, nulla tortor aliquet ligula, non varius nulla nisl ac augue. Nunc a lorem et augue ultrices lobortis sed id libero. Ut ut libero eget arcu finibus sollicitudin et a enim. Aenean tellus lorem, fringilla at dui nec, placerat mattis lacus. Sed tempor leo velit, quis posuere ante fermentum nec. Aliquam a ante id purus feugiat bibendum. Maecenas rhoncus rutrum nisi a cursus. Nulla facilisi. Pellentesque non condimentum tellus. Integer a arcu id ante pretium euismod. Quisque fermentum egestas dui nec lobortis. Nullam interdum dui molestie erat maximus commodo. Ut hendrerit arcu augue, ac commodo ipsum auctor in. In ac justo turpis.
Curabitur nunc libero, vehicula quis fermentum sit amet, tincidunt sed mauris. Maecenas euismod, nulla eget viverra aliquet, mauris eros pellentesque justo, elementum lobortis felis sapien mollis enim. Aenean suscipit tellus egestas venenatis congue. Duis sollicitudin mi et mauris egestas, nec ullamcorper leo convallis. Nulla sed leo eget quam ullamcorper feugiat. Etiam porta a diam nec varius. Etiam sollicitudin sodales diam, id dictum felis ullamcorper a. Nullam quis metus molestie, efficitur leo sed, dignissim dui. Praesent blandit accumsan sagittis. Curabitur non gravida dolor. Donec non vulputate odio. Nunc dapibus leo elit, quis tempus orci eleifend at.
Suspendisse dictum blandit dolor, vel elementum nulla consectetur eu. Nam vitae feugiat diam. Nullam dui lacus, porttitor non lacus sit amet, lobortis semper neque. Nam varius quam at metus tincidunt, sit amet gravida enim bibendum. Duis a diam vulputate, eleifend nisi id, dapibus augue. Nam id blandit tellus. Mauris lacinia ex sit amet est tempor luctus. Donec consequat pellentesque enim, id dapibus ex. Curabitur nec dignissim felis, eu molestie mauris. Aenean nec interdum odio. Sed ac tristique erat.
Curabitur lectus risus, malesuada nec justo eu, commodo pretium libero. Nullam aliquet maximus iaculis. Mauris consequat pharetra eros quis ornare. Vivamus pharetra, velit vel tincidunt viverra, diam sapien euismod dolor, eu euismod lacus nibh sit amet magna. Vestibulum magna nulla, vulputate ac sollicitudin id, sagittis ac arcu. Vivamus pharetra maximus erat, et bibendum arcu placerat eget. Mauris nec tortor id mi molestie ultrices. Integer convallis tempor tellus at consequat.
Nullam eget elementum ante. Curabitur mauris diam, porttitor id neque sit amet, imperdiet rutrum nisl. Etiam eget nisi sit amet nibh fringilla mollis at ac turpis. Sed id mi non nisl commodo ultricies. In hac habitasse platea dictumst. Morbi odio arcu, hendrerit at risus vitae, consectetur pretium enim. Ut eu rutrum dui, ultrices sagittis dui. Etiam vestibulum turpis massa, nec scelerisque diam hendrerit nec. Aliquam erat volutpat. Cras vitae tellus at sem tincidunt egestas. Cras nisl justo, eleifend a accumsan sit amet, vulputate quis sapien. Curabitur efficitur elementum lorem.
Praesent bibendum, velit vitae pulvinar tempor, nulla tortor aliquet ligula, non varius nulla nisl ac augue. Nunc a lorem et augue ultrices lobortis sed id libero. Ut ut libero eget arcu finibus sollicitudin et a enim. Aenean tellus lorem, fringilla at dui nec, placerat mattis lacus. Sed tempor leo velit, quis posuere ante fermentum nec. Aliquam a ante id purus feugiat bibendum. Maecenas rhoncus rutrum nisi a cursus. Nulla facilisi. Pellentesque non condimentum tellus. Integer a arcu id ante pretium euismod. Quisque fermentum egestas dui nec lobortis. Nullam interdum dui molestie erat maximus commodo. Ut hendrerit arcu augue, ac commodo ipsum auctor in. In ac justo turpis.
Curabitur nunc libero, vehicula quis fermentum sit amet, tincidunt sed mauris. Maecenas euismod, nulla eget viverra aliquet, mauris eros pellentesque justo, elementum lobortis felis sapien mollis enim. Aenean suscipit tellus egestas venenatis congue. Duis sollicitudin mi et mauris egestas, nec ullamcorper leo convallis. Nulla sed leo eget quam ullamcorper feugiat. Etiam porta a diam nec varius. Etiam sollicitudin sodales diam, id dictum felis ullamcorper a. Nullam quis metus molestie, efficitur leo sed, dignissim dui. Praesent blandit accumsan sagittis. Curabitur non gravida dolor. Donec non vulputate odio. Nunc dapibus leo elit, quis tempus orci eleifend at.
Suspendisse dictum blandit dolor, vel elementum nulla consectetur eu. Nam vitae feugiat diam. Nullam dui lacus, porttitor non lacus sit amet, lobortis semper neque. Nam varius quam at metus tincidunt, sit amet gravida enim bibendum. Duis a diam vulputate, eleifend nisi id, dapibus augue. Nam id blandit tellus. Mauris lacinia ex sit amet est tempor luctus. Donec consequat pellentesque enim, id dapibus ex. Curabitur nec dignissim felis, eu molestie mauris. Aenean nec interdum odio. Sed ac tristique erat.
Curabitur lectus risus, malesuada nec justo eu, commodo pretium libero. Nullam aliquet maximus iaculis. Mauris consequat pharetra eros quis ornare. Vivamus pharetra, velit vel tincidunt viverra, diam sapien euismod dolor, eu euismod lacus nibh sit amet magna. Vestibulum magna nulla, vulputate ac sollicitudin id, sagittis ac arcu. Vivamus pharetra maximus erat, et bibendum arcu placerat eget. Mauris nec tortor id mi molestie ultrices. Integer convallis tempor tellus at consequat.
Nullam eget elementum ante. Curabitur mauris diam, porttitor id neque sit amet, imperdiet rutrum nisl. Etiam eget nisi sit amet nibh fringilla mollis at ac turpis. Sed id mi non nisl commodo ultricies. In hac habitasse platea dictumst. Morbi odio arcu, hendrerit at risus vitae, consectetur pretium enim. Ut eu rutrum dui, ultrices sagittis dui. Etiam vestibulum turpis massa, nec scelerisque diam hendrerit nec. Aliquam erat volutpat. Cras vitae tellus at sem tincidunt egestas. Cras nisl justo, eleifend a accumsan sit amet, vulputate quis sapien. Curabitur efficitur elementum lorem.
Praesent bibendum, velit vitae pulvinar tempor, nulla tortor aliquet ligula, non varius nulla nisl ac augue. Nunc a lorem et augue ultrices lobortis sed id libero. Ut ut libero eget arcu finibus sollicitudin et a enim. Aenean tellus lorem, fringilla at dui nec, placerat mattis lacus. Sed tempor leo velit, quis posuere ante fermentum nec. Aliquam a ante id purus feugiat bibendum. Maecenas rhoncus rutrum nisi a cursus. Nulla facilisi. Pellentesque non condimentum tellus. Integer a arcu id ante pretium euismod. Quisque fermentum egestas dui nec lobortis. Nullam interdum dui molestie erat maximus commodo. Ut hendrerit arcu augue, ac commodo ipsum auctor in. In ac justo turpis.
Curabitur nunc libero, vehicula quis fermentum sit amet, tincidunt sed mauris. Maecenas euismod, nulla eget viverra aliquet, mauris eros pellentesque justo, elementum lobortis felis sapien mollis enim. Aenean suscipit tellus egestas venenatis congue. Duis sollicitudin mi et mauris egestas, nec ullamcorper leo convallis. Nulla sed leo eget quam ullamcorper feugiat. Etiam porta a diam nec varius. Etiam sollicitudin sodales diam, id dictum felis ullamcorper a. Nullam quis metus molestie, efficitur leo sed, dignissim dui. Praesent blandit accumsan sagittis. Curabitur non gravida dolor. Donec non vulputate odio. Nunc dapibus leo elit, quis tempus orci eleifend at.
Quisque fringilla sagittis suscipit. Aenean euismod, neque vitae mollis congue, leo ex feugiat quam, quis blandit nisl neque in nisl. Nunc ultricies libero purus, sed elementum turpis volutpat et. Pellentesque porta dui non cursus ultricies. Phasellus non nibh mattis, iaculis leo eu, fermentum dolor. Suspendisse euismod nisl eu nisi tempus scelerisque. Aliquam non purus imperdiet, aliquet ipsum eget, tempor massa. Maecenas sit amet lectus suscipit, sollicitudin ex a, viverra tellus. Morbi vehicula orci et turpis gravida dictum. In ipsum mi, pharetra id dictum id, congue at mauris. Aenean tincidunt tortor et felis pretium, sagittis viverra arcu semper. Mauris eleifend suscipit arcu vel luctus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. In nec felis at augue convallis egestas a eu nulla. Interdum et malesuada fames ac ante ipsum primis in faucibus. Curabitur in odio lectus.
Suspendisse sed lectus orci. Sed sit amet ultrices odio, vitae egestas justo. Vivamus sed elit sed mauris venenatis ullamcorper nec at ligula. Quisque aliquet sem nec felis lacinia placerat. Etiam consequat ipsum id mauris rhoncus, sed condimentum ex convallis. Cras finibus libero dui, eu fermentum metus ultricies nec. Phasellus maximus suscipit elit eget congue. Nulla facilisi. " >testCatalog/from/coppyByMapping.txt

printf "To delete" > testCatalog/to/thisFileShuldBeRemoved.txt

echo "Preparing files successfull"